In [2]:
import pandas as pd

In [3]:
data = pd.read_csv("/kaggle/input/datasets/aiexplorer77/from-fuel-to-electric-the-ev-transition-dataset/global_ev_adoption_behavior_2026.csv")

In [4]:
data.head()

,age,annual_income,education_level,city_type,daily_commute_km,weekly_travel_distance_km,current_vehicle_type,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,...,environmental_awareness_score,government_incentive_awareness,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost
0,56,23019.0,High School,Suburban,39.8,205.7,Hatchback,6.1,317.1,3.9,...,8.3,6.4,5.2,4.6,3.5,6.9,0,High,199.8,28.5
1,46,26440.0,High School,Suburban,34.6,218.4,Sedan,4.4,290.0,4.5,...,7.8,10.0,5.7,5.5,7.4,6.9,1,High,139.8,22.9
2,46,57167.0,PhD,Suburban,30.5,177.7,Sedan,0.4,201.4,6.3,...,7.6,6.4,7.8,5.3,6.2,6.8,0,High,158.0,38.5
3,23,15841.0,Master,Suburban,44.6,325.9,SUV,0.0,407.3,5.2,...,6.2,5.6,5.1,7.9,5.7,7.2,0,Low,207.0,45.0
4,50,51571.0,Master,Urban,52.4,281.0,SUV,5.2,458.4,4.3,...,9.7,9.9,8.2,2.6,4.7,8.1,0,High,195.6,43.9

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             50000 non-null  int64
 1   annual_income                   50000 non-null  float64
 2   education_level                 49500 non-null  object
 3   city_type                       50000 non-null  object
 4   daily_commute_km                50000 non-null  float64
 5   weekly_travel_distance_km       50000 non-null  float64
 6   current_vehicle_type            50000 non-null  object
 7   vehicle_age_years               50000 non-null  float64
 8   fuel_expense_per_month          50000 non-null  float64
 9   charging_station_accessibility  49500 non-null  float64
 10  nearest_charging_station_km     50000 non-null  float64
 11  home_charging_available         50000 non-null  int64
 12  electricity_cost_per_kwh        50000 non-null  float64
 13  environmental_awareness_score   50000 non-null  float64
 14  government_incentive_awareness  50000 non-null  float64
 15  technology_affinity_score       50000 non-null  float64
 16  range_anxiety_score             50000 non-null  float64
 17  battery_replacement_concern     50000 non-null  float64
 18  ev_knowledge_score              49500 non-null  float64
 19  previous_ev_experience          50000 non-null  int64
 20  ev_adoption_likelihood          50000 non-null  object
 21  monthly_energy_consumption_kwh  50000 non-null  float64
 22  monthly_charging_cost           50000 non-null  float64
dtypes: float64(16), int64(3), object(4)
memory usage: 8.8+ MB

In [6]:
data.isnull().sum()

age                                 0
annual_income                       0
education_level                   500
city_type                           0
daily_commute_km                    0
weekly_travel_distance_km           0
current_vehicle_type                0
vehicle_age_years                   0
fuel_expense_per_month              0
charging_station_accessibility    500
nearest_charging_station_km         0
home_charging_available             0
electricity_cost_per_kwh            0
environmental_awareness_score       0
government_incentive_awareness      0
technology_affinity_score           0
range_anxiety_score                 0
battery_replacement_concern         0
ev_knowledge_score                500
previous_ev_experience              0
ev_adoption_likelihood              0
monthly_energy_consumption_kwh      0
monthly_charging_cost               0
dtype: int64

In [7]:
# Data preprocessing 

from sklearn.impute import SimpleImputer

num_imputer = SimpleImputer(strategy='median')

data[['charging_station_accessibility', 'ev_knowledge_score']] = num_imputer.fit_transform(
    data[['charging_station_accessibility', 'ev_knowledge_score']]
)

freq_imputer = SimpleImputer(strategy='most_frequent')
data[['education_level']] = freq_imputer.fit_transform(data[['education_level']])

In [8]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 23 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   age                             50000 non-null  int64
 1   annual_income                   50000 non-null  float64
 2   education_level                 50000 non-null  object
 3   city_type                       50000 non-null  object
 4   daily_commute_km                50000 non-null  float64
 5   weekly_travel_distance_km       50000 non-null  float64
 6   current_vehicle_type            50000 non-null  object
 7   vehicle_age_years               50000 non-null  float64
 8   fuel_expense_per_month          50000 non-null  float64
 9   charging_station_accessibility  50000 non-null  float64
 10  nearest_charging_station_km     50000 non-null  float64
 11  home_charging_available         50000 non-null  int64
 12  electricity_cost_per_kwh        50000 non-null  float64
 13  environmental_awareness_score   50000 non-null  float64
 14  government_incentive_awareness  50000 non-null  float64
 15  technology_affinity_score       50000 non-null  float64
 16  range_anxiety_score             50000 non-null  float64
 17  battery_replacement_concern     50000 non-null  float64
 18  ev_knowledge_score              50000 non-null  float64
 19  previous_ev_experience          50000 non-null  int64
 20  ev_adoption_likelihood          50000 non-null  object
 21  monthly_energy_consumption_kwh  50000 non-null  float64
 22  monthly_charging_cost           50000 non-null  float64
dtypes: float64(16), int64(3), object(4)
memory usage: 8.8+ MB

In [9]:
# Data Encoding 

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data["ev_adoption_likelihood"] = le.fit_transform(data["ev_adoption_likelihood"])

col = ["city_type","current_vehicle_type"]
data = pd.get_dummies(data, columns=col, drop_first=True, dtype=int)

In [10]:
data.head(10)

,age,annual_income,education_level,daily_commute_km,weekly_travel_distance_km,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,nearest_charging_station_km,home_charging_available,...,ev_knowledge_score,previous_ev_experience,ev_adoption_likelihood,monthly_energy_consumption_kwh,monthly_charging_cost,city_type_Suburban,city_type_Urban,current_vehicle_type_SUV,current_vehicle_type_Sedan,current_vehicle_type_Truck
0,56,23019.0,High School,39.8,205.7,6.1,317.1,3.9,9.5,1,...,6.9,0,0,199.8,28.5,1,0,0,0,0
1,46,26440.0,High School,34.6,218.4,4.4,290.0,4.5,11.6,1,...,6.9,1,0,139.8,22.9,1,0,0,1,0
2,46,57167.0,PhD,30.5,177.7,0.4,201.4,6.3,6.4,1,...,6.8,0,0,158.0,38.5,1,0,0,1,0
3,23,15841.0,Master,44.6,325.9,0.0,407.3,5.2,8.8,0,...,7.2,0,1,207.0,45.0,1,0,1,0,0
4,50,51571.0,Master,52.4,281.0,5.2,458.4,4.3,0.5,0,...,8.1,0,0,195.6,43.9,0,1,1,0,0
5,23,19315.0,Bachelor,32.8,167.6,4.0,275.7,8.0,2.0,0,...,4.9,0,1,118.1,14.1,0,1,1,0,0
6,53,52110.0,High School,14.0,99.0,2.7,90.1,6.8,12.4,0,...,7.3,0,2,90.9,9.6,1,0,0,0,0
7,69,126618.0,High School,40.9,314.9,1.7,391.6,9.6,0.5,1,...,7.4,0,0,203.3,65.0,0,1,0,0,1
8,53,62712.0,Bachelor,42.1,256.8,3.1,397.9,8.3,15.2,1,...,6.6,0,2,193.3,28.5,0,1,0,0,0
9,69,41775.0,High School,40.9,262.3,7.0,363.9,4.7,11.4,1,...,5.1,0,1,202.4,47.5,0,0,0,1,0

In [11]:
X = data.drop(columns = ["education_level","ev_adoption_likelihood", "monthly_energy_consumption_kwh", "monthly_charging_cost"], axis = 1)
Y = data["ev_adoption_likelihood"]

In [12]:
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(
    X,Y,
    test_size=0.4,
    random_state=42
)

In [13]:
X_train.head()

,age,annual_income,daily_commute_km,weekly_travel_distance_km,vehicle_age_years,fuel_expense_per_month,charging_station_accessibility,nearest_charging_station_km,home_charging_available,electricity_cost_per_kwh,...,technology_affinity_score,range_anxiety_score,battery_replacement_concern,ev_knowledge_score,previous_ev_experience,city_type_Suburban,city_type_Urban,current_vehicle_type_SUV,current_vehicle_type_Sedan,current_vehicle_type_Truck
18306,28,13381.0,42.9,337.6,7.4,361.2,1.5,13.1,1,0.14,...,8.1,2.7,6.6,8.8,0,1,0,1,0,0
49528,54,53421.0,46.4,268.8,8.4,375.1,4.4,13.1,1,0.23,...,7.4,2.9,5.6,8.4,0,0,0,1,0,0
44745,45,58583.0,28.5,217.2,4.8,215.5,5.7,0.5,1,0.25,...,7.4,2.6,4.9,6.9,0,0,1,0,1,0
46827,31,35921.0,32.7,248.3,8.8,240.5,6.8,4.2,1,0.11,...,9.8,5.8,4.7,9.9,1,0,1,0,1,0
27531,47,75603.0,23.3,141.7,7.0,136.3,7.1,0.8,1,0.11,...,8.4,2.6,4.0,8.1,0,0,1,1,0,0

In [14]:
Y_train.head()

18306    0
49528    0
44745    0
46827    0
27531    0
Name: ev_adoption_likelihood, dtype: int64

In [15]:
# Data Scaling

from sklearn.preprocessing import StandardScaler

scale = StandardScaler()

X_train = scale.fit_transform(X_train)
X_test = scale.transform(X_test)

# SVM Classifier

In [16]:
# Default kernel "RBF"

from sklearn.svm import SVC

svc = SVC()
svc.fit(X_train, Y_train)

SVC()

In [17]:
Y_pred = svc.predict(X_test)
Y_pred_t = svc.predict(X_train)

In [18]:
from sklearn.metrics import accuracy_score

print(f"Accuracy for train data: {accuracy_score(Y_train,Y_pred_t)*100} %")
print(f"Accuracy for test data: {accuracy_score(Y_test,Y_pred)*100} %")

Accuracy for train data: 89.61 %
Accuracy for test data: 86.72999999999999 %

## Different Kernel Methods

In [19]:
svc = SVC(kernel = "linear")
svc.fit(X_train, Y_train)

Y_pred = svc.predict(X_test)
Y_pred_t = svc.predict(X_train)

print(f"Accuracy for train data: {accuracy_score(Y_train,Y_pred_t)*100} %")
print(f"Accuracy for test data: {accuracy_score(Y_test,Y_pred)*100} %")

Accuracy for train data: 87.57333333333334 %
Accuracy for test data: 87.155 %

In [20]:
svc = SVC(kernel = "poly")
svc.fit(X_train, Y_train)

Y_pred = svc.predict(X_test)
Y_pred_t = svc.predict(X_train)

print(f"Accuracy for train data: {accuracy_score(Y_train,Y_pred_t)*100} %")
print(f"Accuracy for test data: {accuracy_score(Y_test,Y_pred)*100} %")

Accuracy for train data: 89.15333333333334 %
Accuracy for test data: 86.37 %