In [125]:
import pandas as pd

In [126]:
loan_data = pd.read_csv("/kaggle/input/datasets/premraj25/loan-data/loan_approval_data.csv")

In [127]:
loan_data.head()

,Applicant_ID,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,1.0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2.0,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,3.0,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,4.0,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,5.0,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [128]:
loan_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 20 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Applicant_ID        950 non-null    float64
 1   Applicant_Income    950 non-null    float64
 2   Coapplicant_Income  950 non-null    float64
 3   Employment_Status   950 non-null    object
 4   Age                 950 non-null    float64
 5   Marital_Status      950 non-null    object
 6   Dependents          950 non-null    float64
 7   Credit_Score        950 non-null    float64
 8   Existing_Loans      950 non-null    float64
 9   DTI_Ratio           950 non-null    float64
 10  Savings             950 non-null    float64
 11  Collateral_Value    950 non-null    float64
 12  Loan_Amount         950 non-null    float64
 13  Loan_Term           950 non-null    float64
 14  Loan_Purpose        950 non-null    object
 15  Property_Area       950 non-null    object
 16  Education_Level     950 non-null    object
 17  Gender              950 non-null    object
 18  Employer_Category   950 non-null    object
 19  Loan_Approved       950 non-null    object
dtypes: float64(12), object(8)
memory usage: 156.4+ KB

In [129]:
loan_data.isnull().sum()

Applicant_ID          50
Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [130]:
loan_data = loan_data.drop(columns=["Applicant_ID"],axis=1)

In [131]:
loan_data.head()

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,NaN,Car,Semiurban,Graduate,NaN,Private,No
2,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,NaN,Urban,NaN,Female,Government,Yes
3,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,NaN,Graduate,Male,Private,Yes

In [132]:
loan_data.isnull().sum()

Applicant_Income      50
Coapplicant_Income    50
Employment_Status     50
Age                   50
Marital_Status        50
Dependents            50
Credit_Score          50
Existing_Loans        50
DTI_Ratio             50
Savings               50
Collateral_Value      50
Loan_Amount           50
Loan_Term             50
Loan_Purpose          50
Property_Area         50
Education_Level       50
Gender                50
Employer_Category     50
Loan_Approved         50
dtype: int64

In [133]:
# Data Preprocessing 

from sklearn.impute import SimpleImputer

# For numerical columns

imp_mean = SimpleImputer(strategy="mean")

features_val = ["Applicant_Income","Coapplicant_Income","Age", "Dependents", "Credit_Score", "Existing_Loans", "DTI_Ratio", "Savings", "Collateral_Value", "Loan_Amount", "Loan_Term"]

for col in features_val:
    loan_data[[col]] = imp_mean.fit_transform(loan_data[[col]])

# For Category columns

imp_freq = SimpleImputer(strategy="most_frequent")

features_cat = ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Education_Level", "Employer_Category", "Gender","Loan_Approved"]

for col in features_cat:
    loan_data[[col]] = imp_freq.fit_transform(loan_data[[col]])

In [134]:
loan_data.isnull().sum()

Applicant_Income      0
Coapplicant_Income    0
Employment_Status     0
Age                   0
Marital_Status        0
Dependents            0
Credit_Score          0
Existing_Loans        0
DTI_Ratio             0
Savings               0
Collateral_Value      0
Loan_Amount           0
Loan_Term             0
Loan_Purpose          0
Property_Area         0
Education_Level       0
Gender                0
Employer_Category     0
Loan_Approved         0
dtype: int64

In [135]:
loan_data.head()

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,17795.0,1387.0,Salaried,51.0,Married,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,Personal,Urban,Not Graduate,Female,Private,No
1,2860.0,2679.0,Salaried,46.0,Married,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,48.0,Car,Semiurban,Graduate,Male,Private,No
2,7390.0,2106.0,Salaried,25.0,Single,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,Business,Urban,Graduate,Female,Government,Yes
3,13964.0,8173.0,Salaried,40.0,Married,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,Business,Rural,Graduate,Female,Government,No
4,13284.0,4223.0,Self-employed,31.0,Single,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,Car,Urban,Graduate,Male,Private,Yes

In [136]:
# Encoding for Category Columns

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

feature_encod = ["Employment_Status", "Marital_Status", "Loan_Purpose", "Property_Area", "Education_Level", "Employer_Category", "Gender","Loan_Approved"]

for col in feature_encod:
    loan_data[col] = le.fit_transform(loan_data[col])

In [137]:
loan_data.head(10)

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category,Loan_Approved
0,17795.0,1387.000000,1,51.0,0,0.0,637.0,4.0,0.530000,19403.0,45638.0,16619.0,84.0,4,2,1,0,3,0
1,2860.0,2679.000000,1,46.0,0,3.0,621.0,2.0,0.300000,2580.0,49272.0,38687.0,48.0,1,1,0,1,3,0
2,7390.0,2106.000000,1,25.0,1,2.0,674.0,4.0,0.200000,13844.0,6908.0,27943.0,72.0,0,2,0,0,1,1
3,13964.0,8173.000000,1,40.0,0,2.0,579.0,3.0,0.310000,9553.0,10844.0,27819.0,60.0,0,0,0,0,1,0
4,13284.0,4223.000000,2,31.0,1,2.0,721.0,1.0,0.290000,9386.0,37629.0,12741.0,72.0,1,2,0,1,3,1
5,8265.0,4831.000000,1,53.0,1,1.0,602.0,1.0,0.560000,19522.0,2911.0,9798.0,36.0,3,1,0,1,4,0
6,18850.0,2768.000000,1,58.0,0,0.0,687.0,0.0,0.480000,14635.0,8991.0,26143.0,24.0,3,0,0,1,3,0
7,6426.0,3186.000000,1,47.0,0,2.0,636.0,4.0,0.347263,671.0,11572.0,33747.0,84.0,4,0,0,0,3,0
8,16423.0,5082.455789,1,54.0,0,1.0,729.0,0.0,0.590000,777.0,43066.0,34651.0,36.0,3,1,0,1,3,0
9,13363.0,2599.000000,0,35.0,1,3.0,726.0,1.0,0.347263,3022.0,29693.0,22182.0,60.0,4,0,0,0,1,1

In [138]:
# Building DT model

from sklearn.model_selection import train_test_split

X = loan_data.drop("Loan_Approved", axis = 1)
Y = loan_data["Loan_Approved"]

X.head()

,Applicant_Income,Coapplicant_Income,Employment_Status,Age,Marital_Status,Dependents,Credit_Score,Existing_Loans,DTI_Ratio,Savings,Collateral_Value,Loan_Amount,Loan_Term,Loan_Purpose,Property_Area,Education_Level,Gender,Employer_Category
0,17795.0,1387.0,1,51.0,0,0.0,637.0,4.0,0.53,19403.0,45638.0,16619.0,84.0,4,2,1,0,3
1,2860.0,2679.0,1,46.0,0,3.0,621.0,2.0,0.30,2580.0,49272.0,38687.0,48.0,1,1,0,1,3
2,7390.0,2106.0,1,25.0,1,2.0,674.0,4.0,0.20,13844.0,6908.0,27943.0,72.0,0,2,0,0,1
3,13964.0,8173.0,1,40.0,0,2.0,579.0,3.0,0.31,9553.0,10844.0,27819.0,60.0,0,0,0,0,1
4,13284.0,4223.0,2,31.0,1,2.0,721.0,1.0,0.29,9386.0,37629.0,12741.0,72.0,1,2,0,1,3

In [139]:
Y.head()

0    0
1    0
2    1
3    0
4    1
Name: Loan_Approved, dtype: int64

In [140]:
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,
    test_size = 0.3,                                                
    random_state = 42
)

In [141]:
from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()
model.fit(X_train, Y_train)

DecisionTreeClassifier()

In [148]:
acc = model.score(X_test, Y_test)
print(f"Accuracy of ML Model for Loan approval: {acc*100} %")

Accuracy of ML Model for Loan approval: 87.33333333333333 %